apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-redis-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /tmp/local/cart-redis-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/cart-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-mongo-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/catalog-mongo-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/catalog-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /tmp/local/order-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-postgres-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/order-postgres-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-mongo-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-mongo-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-redis-pv-${NS}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-redis-pv-${NS}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE_NAME}
