apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-redis-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /tmp/local/cart-redis-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/cart-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-mongo-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/catalog-mongo-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/catalog-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /tmp/local/order-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-postgres-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/order-postgres-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-mongo-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-mongo-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-redis-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem  
  local:
    path: /tmp/local/users-redis-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
